baseURL = 'https://theinvisiblefoe.github.io/'
languageCode = 'en-us'
title = 'lolcat'

theme = "hello-friend-ng"
# theme = "FixIt"
pagination.pagerSize = 10
# [module]
# [[module.imports]]
#     path = 'github.com/hugomods/katex'

[module]
[[module.imports]]
path = 'github.com/hugomods/images'
disable = false

[[module.imports]]
path = "github.com/KKKZOZ/hugo-admonitions"
# [[module.imports]]
#   path = "my-theme"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
math = true

# Subtitle for home
homeSubtitle = "“Now, I may be an idiot, but there's one thing I am not sir, and that, sir, is an idiot.” "

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false
# Enable theme toggle
# 
# This options enables the theme toggle for the theme. 
# Per default, this option is off. 
# The theme is respecting the prefers-color-scheme of the operating system. 
# With this option on, the page user is able to set the scheme he wants. 
enableThemeToggle = true
# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

# Metadata mostly used in document's head
description = "My new homepage or blog"
keywords = "homepage, blog"
images = [""]
[[params.social]]
name = "lastfm"
icon = "Last.fm"
url = "https://www.last.fm/user/Sab2004"
weight = 40
[[params.social]]
name = "github"
icon = "github"
url = "https://github.com/TheInvisibleFoe"
weight = 40

[taxonomies]
category = "blog"
tag = "tags"
series = "series"


[languages]
[languages.en]
title = "Welcome to the Octopus's Garden"
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

[languages.en.params]
subtitle = "Heya people, I am Sabarno Saha. Just here testing out my website"

[languages.en.params.logo]
logoText = "Octopus's Garden"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 1
[[menu.main]]
identifier = "links"
name = "Stuff"
url = "/links"
weight = 1
[[menu.main]]
identifier = "about"
name = "About me"
url = "/about"
weight = 2
[[menu.main]]
identifier = "notes"
name = "Notes"
url = "/notes"
weight = 2
# [markup]
# [markup.goldmark]
# [markup.goldmark.extensions]
# [markup.goldmark.extensions.passthrough]
# enable = true
# [markup.goldmark.extensions.passthrough.delimiters]
# block = [['\[', '\]'], ['$$', '$$']]
# inline = [['\(', '\)']]
#

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
